# Generated by Django 5.2.7 on 2025-10-20 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo_link', models.URLField(blank=True, null=True)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('batch', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('is_por_holder', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-is_por_holder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('date_published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('blog_content', models.TextField(blank=True, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('blog_image_link', models.URLField(blank=True, null=True)),
                ('blog_image_file', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/')),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('medium_link', models.URLField(blank=True, null=True)),
                ('other_links', models.TextField(blank=True, null=True)),
                ('views_count', models.IntegerField(blank=True, default=0, null=True)),
                ('author_members', models.ManyToManyField(blank=True, related_name='blog_posts', to='main.member')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Short project description', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed project description', null=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('technologies_used', models.CharField(blank=True, help_text='Comma-separated technologies', max_length=500, null=True)),
                ('tech_stack', models.TextField(blank=True, help_text='Detailed tech stack', null=True)),
                ('heroSectionImageLink', models.URLField(blank=True, null=True)),
                ('hero_section_image_file', models.ImageField(blank=True, null=True, upload_to='projects/hero/')),
                ('image_1_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('documentation_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('team_lead', models.CharField(blank=True, max_length=250, null=True)),
                ('collaborators', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived'), ('planned', 'Planned')], default='ongoing', max_length=50, null=True)),
                ('text_1', models.TextField(blank=True, help_text='Additional content section 1', null=True)),
                ('text_2', models.TextField(blank=True, help_text='Additional content section 2', null=True)),
                ('text_3', models.TextField(blank=True, help_text='Additional content section 3', null=True)),
                ('features', models.TextField(blank=True, help_text='Key features', null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('learnings', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0, help_text='Display order', null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('team_members', models.ManyToManyField(blank=True, related_name='projects', to='main.member')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-start_date'],
            },
        ),
    ]
